### PR TITLE
Gc fe foundation

### PR DESCRIPTION
**Pull request by isaacdenny**
# Description

Started the front end for our ground station. Features a navigation bar with routing via react-router-dom and a procedure menu to create new procedures. also added dummy api endpoint

Fixes # (issue)
#63 

## Bug Fix or Feature

- [ ] Bug
- [x] Feature
- [ ] Other

# Testing Instructions

- [x] start containers
- [x] visit localhost:3000
- [x] navigate to procedures menu
- [x] create procedure (create button sends request)
- [x] see printed procedure in json in console

## Linting

- [ ] I've linted my code

### CODE REVIEW

**Review by dignojrteogalbo — CHANGES_REQUESTED** [review]
One thing missing is that there isn't any way to link from one procedure to another procedure. The last task's nextTask points to an index not available in the current procedure. If Unity were to take this in, I believe an index out of bounds error would throw if they tried to use that index. Format matches the schema and the front end looks good.

**Review by dignojrteogalbo — CHANGES_REQUESTED** [review]
I got this error when viewing the page.
image

**Comment by isaacdenny** [comment]
> I got this error when viewing the page. image

My b... should be fixed now

**Review by dignojrteogalbo — APPROVED** [review]
Looks good, one thing that could improve it is displaying the JSON text directly in the web page itself but that could be something to be resolved in a later issue. For now, the procedures endpoint prints it to the console but I'm assuming we will create a procedures table to store these in at a later PR.

**Pull request merged**
