### PR TITLE
A basic telemetry api and client with logging

### PR DESCRIPTION
**Pull request by cburnout**
# Description

This fakes a very simple telemetry api to show how to create event types in the event manager. It also has the events sent out over another api endpoint for logging (no logging levels yet)

Fixes # (issue)
I need to make one

## Bug Fix or Feature

- [ ] Bug
- [x] Feature
- [ ] Other

# Testing Instructions

- [ ] Start Docker Compose
- [ ] Start the Telemetry scene
- [ ] See that the numbers are logged in the unity console
- [ ] See that the logging endpoint is logging a json of the event that was fired off

## Linting

- [x] I've linted my code

### CODE REVIEW

**Review by isaacdenny — APPROVED** [review]
Everything looks good. The C# and python is clean and most changed files were just renamed or moved.

**Comment by isaacdenny** [comment]
I resolved some of the merge conflicts: just some issues with main not having packages here, and new methods in the api

**Review by isaacdenny — APPROVED** [review]
lookin good

**Comment by cburnell** [comment]
Thanks for the merge conflict fixes I was just about to go home and them
but that's a great bday present

**Pull request merged**
