### PR TITLE
Lmcc updates

### LINKED ISSUE #161: LMCC EV Telemetry - Display Space Suit Charts - Primary
Reference #137 

Given: Space suit data from TSS  
When: IVA navigates to "Biometrics and Spacesuit Data" page in LMCC 
Then: Displays space suit time-series charts (reference pg. 9 in proposal)

### LINKED ISSUE #162: LMCC EV Telemetry - Display Biometric Charts - Primary
Reference #137 

Given: Biometric data from TSS  
When: IVA navigates to "Biometrics and Spacesuit Data" page in LMCC 
Then: Displays biometric time-series charts (reference pg. 9 of proposal)

### LINKED ISSUE #200: LMCC Mock Biometrics Source
Implement mock datastore to get biometrics from for UI dev

### PR DESCRIPTION
**Pull request by Aetheris743**
# Description

This adds a mock store that can be used for testing and displays the store on the biometrics table page

Closes #200

## Bug Fix or Feature

Feature/Work in progress

# Testing Instructions

- Open LMCC
- Navigate to `/biometrics`
   - Verify that the are changing values

## Linting

- [x] I've linted my code

### CODE REVIEW

**Review by dignojrteogalbo — COMMENTED** [review]
Might need to change the keys of these values to adhere to the TSS telemetry response body. Will that be in a later change once MCP datastore is finalized?

**Comment by Aetheris743** [comment]
Yeah, if it work for you lets create the final one once we have the actual websocket connection and API requests figured out.

**Comment by Aetheris743** [comment]
I was mainly planning on using this for UI development so we can get that done in the meantime

**Review by dignojrteogalbo — APPROVED** [review]
It works for me.

**Pull request merged**
